name: PJ weekly meetup

on:
  schedule:
    - cron: '0 10 * * *'  # KST 19:00 ~

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test
      env:
        SLACK_WEB_HOOK: ${{ secrets.SLACK_WEB_HOOK}}
        PYCON_ICON_URL: ${{ secrets.PYCON_ICON_URL}}
        PYCON_WEEKLY_DOC_URL: ${{ secrets.PYCON_WEEKLY_DOC_URL}}
        ZOOM_LINK: ${{ secrets.ZOOM_LINK}}
        
      run: |
        python weeklymeetup_noti_1hour_ago.py
